server {
    listen 443 ssl;
    
    root /var/www/html;
    
    server_name souel-bo.42.fr;

    ssl_certificate     /etc/ssl/certs/souel-bo.42.fr.cert;
    ssl_certificate_key /etc/ssl/certs/souel-bo.42.fr.key;
 
    
    ssl_protocols TLSv1.3;

    # 7. Location block dedicated to serving static files
    location / {
        try_files $uri $uri/ =404;
    }
}